# Generated by Django 2.1.1 on 2018-11-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('subtitulo', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('categoria', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
                ('editor', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, upload_to='post_image')),
            ],
        ),
    ]
