# Generated by Django 2.1.1 on 2018-11-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20181112_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
