# Generated by Django 2.1.1 on 2018-11-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_auto_20181114_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
