# Generated by Django 2.1.1 on 2018-11-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_libro_link_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
