# Generated by Django 2.1.1 on 2018-11-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_auto_20181116_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
